### PR TITLE
Theme переместил в util

### PR DESCRIPTION
**Pull request by kloun**

### CODE REVIEW

**Comment by kloun** [comment]
[INFO] Compiling 60 Scala sources and 253 Java sources to /home/travis/build/maxcom/lorsource/target/classes...
[ERROR] /home/travis/build/maxcom/lorsource/src/main/scala/ru/org/linux/user/EditProfileController.scala:26: object Theme is not a member of package ru.org.linux.site
[ERROR] import ru.org.linux.site.{BadInputException, DefaultProfile, Template, Theme}
[ERROR]        ^
[ERROR] /home/travis/build/maxcom/lorsource/src/main/scala/ru/org/linux/user/EditProfileController.scala:50: not found: value Theme
[ERROR]     val nonDeprecatedThemes = Theme.THEMES.asScala.toVector.filterNot(_.isDeprecated).map(_.getId)cala 2.12.1. Compiling...
[INFO]   Compilation completed in 26.683 s
[INFO] Compiling 60 Scala sources and 253 Java sources to /home/travis/build/maxcom/lorsource/target/classes...
[ERROR] /home/travis/build/maxcom/lorsource/src/main/scala/ru/org/linux/user/EditProfileController.scala:26: object Theme is not a member of package ru.org.linux.site
[ERROR] import ru.org.linux.site.{BadInputException, DefaultProfile, Template, Theme}
[ERROR]        ^
[ERROR] /home/travis/build/maxcom/lorsource/src/main/scala/ru/org/linux/user/EditProfileController.scala:50: not found: value Theme
[ERROR]     val nonDeprecatedThemes = Theme.THEMES.asScala.toVector.filterNot(_.isDeprecated).map(_.getId)

@maxcom я эти ошибки вроде поправил, а травис старье юзает.
что делать?

**Comment by kloun** [comment]
@maxcom ответь.

**Comment by maxcom** [comment]
зачем?

**Comment by kloun** [comment]
Класс theme - это как вспомогательный же, не нравятся мне каталоги site и spring.

**Pull request closed without merging**
